name: Mirror to San Pablo

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # Magia pura: evita que GitHub pise nuestro Token

      - name: Mirror to Target Repository
        env:
          TARGET_REPO: https://x-access-token:${{ secrets.ENTERPRISE_PAT }}@github.com/rdericosanpablo-commits/ERP-R-DE-RICO-SAN-PABLO.git
        run: |
          git push --mirror $TARGET_REPO
